### ISSUE TITLE
[Bug] Consecutive bullets getting merged into one in reading view

### ISSUE THREAD

**Issue by cs-mshah** [ordidxzero/obsidian-external-favicon#1]
The plugin is pretty amazing. But there are cases when consecutive bullets having links get combined to a single line. Here is what I mean:
In live preview:
![image](https://user-images.githubusercontent.com/56499208/227722118-4d2a46aa-ef09-4a8e-8e8a-3548b50c0611.png)

Reading mode:
![image](https://user-images.githubusercontent.com/56499208/227722157-17dad668-485f-4b28-a0a5-1fbcbe5bbb73.png)

You can see the grey bullet inside the awesome obsidian github link merged with the plugin developer docs favicon.

**Comment by cs-mshah** [comment]
It would also be great to have an option to view favicons in live preview mode.

**Comment by ordidxzero** [comment]
Thank you so much for using my plugin! It's very meaningful that you left the first issue of my life. I've fixed the bug you left me. This plugin was rejected because it had a [other plugin](https://github.com/joethei/obsidian-link-favicon) that works the same thing, but thank you again for using it. We will continue maintenance, but for the convenience of updating, we recommend using a plug-in that is officially registered with Obsidian.

**Comment by ordidxzero** [comment]
I also want to implement it so that I can see it in preview mode, but I can't implement that function. This is because in preview mode, there is no way to determine the address of the external link registered in the link block.
