### ISSUE TITLE
Plugin doesn't seem to do anything

### ISSUE THREAD

**Issue by papatistos** [ordidxzero/obsidian-external-favicon#2]
I have installed the plugin but it doesn't seem to do anything. All my external links still look exactly the same and when I add new links, they are rendered in the same way as before (w/o favicons).

I am on obsidian 1.1.16.

**Comment by ordidxzero** [comment]
Can you take a screenshot your obsidian?

**Comment by papatistos** [comment]
What do you want a screenshot of?

**Comment by ordidxzero** [comment]
If you have the plug-in installed, would you mind taking a screenshot of the note in preview mode instead of editor mode? I would greatly appreciate it.

**Comment by papatistos** [comment]
I'm not sure what exactly you are asking for. When you say "preview mode" and "editor mode", you are using the terminology of the legacy editor (which is no longer maintained). In current versions of Obsidian, there are three modes:
1. Editing view (Source mode)
2. Editing view (Live preview mode) 
3. Reading view.

Since Reading view was previously called "preview mode", I assume that is what you want, so, here is a screenshot of a note in reading view:
![Obsidian-2023-04-13 at 12 49 08@2x](https://user-images.githubusercontent.com/3662750/231736519-d63f1911-4147-45bf-9da1-17911aa31f4f.png)

**Comment by ordidxzero** [comment]
The sentence can be unnatural because of the translator.

This is my first time developing a plugin and releasing it to the public, so I'm very sorry if I didn't communicate in the right words. Thank you for your kindness in pointing this out.
1. turn off the plugin and turn off Obsidian completely.
2. turn on Obsidian, then turn on the plugin and turn off Obsidian again.
3. Turn on Obsidian and it looks fine.

I'm new to developing plugins and didn't think anyone would use my plugin, so I've been fiddling around trying to upgrade it slowly, and now I'm having this problem. As an aspiring developer, I'd love to be able to solve problems in an elegant way, but I'm really sorry I have to give you this solution.
